name: CI

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3.9 -m pip install nox
      - name: Lint the code
        run: nox -s lint

# TMP : not ready just yet...
#  package:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#      - name: Set up Python 3.7
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.7
#      - name: Check packages
#        run: |
#          python3.7 -m pip install wheel twine rstcheck;
#          python3.7 setup.py sdist bdist_wheel;
#          rstcheck README.rst CHANGES.rst
#          python3.7 -m twine check dist/*

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]  #, macos-latest, windows-latest]
        experimental: [false]
#        include:
#          - python-version: 3.9
#            os: ubuntu-latest
#            experimental: true

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.python-version }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set Up Python 3.9 to run nox
        if: matrix.python-version != '3.9'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: python -m pip install --upgrade nox

      - name: Run Tests
        run: nox -s tests-${{ matrix.python-version }} --error-on-missing-interpreters
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
